### ISSUE TITLE
let not treated like var

### ISSUE THREAD

**Issue by raybooysen** [voronianski/oceanic-next-theme#29] opened 2015-11-24 14:59 UTC
As per the screenshot, let is not treated with the same colour as var.
![image](https://cloud.githubusercontent.com/assets/461957/11370502/febdec8a-92bb-11e5-941c-c1bce234f23a.png)

**Comment by voronianski** [comment] 2015-11-24 18:46
@raybooysen that's strange, we have it fine on our machines, what is the version of [babel-sublime](https://github.com/acdlite/flummox/issues) package on your machine?

**Comment by raybooysen** [comment] 2015-11-24 22:05
v8.6.2

**Comment by voronianski** [comment] 2015-11-29 10:40
And what version of Oceanic Next and your OS? I cannot reproduce this on Mac OS X and Windows for now.

**Comment by raybooysen** [comment] 2015-12-01 15:17
Using Windows 10
Oceanic Next = 0.1.8

**Comment by flekschas** [comment] 2015-12-02 16:00
Same here on Mac OS X `v10.10`. I am also using OceanNext `v0.1.8` and Babel-sublime `v8.6.2`.

**Comment by ianwith** [comment] 2016-01-08 16:01
+1

**Comment by voronianski** [comment] 2016-04-02 10:52
Do you, guys, still have this issue?

**Comment by ryanzec** [comment] 2016-04-08 00:01
Works fine for me.

OS X: 10.11.3
Babel Sublime: 8.6.3
Ocean Next: 0.1.11

**Comment by voronianski** [comment] 2016-04-08 08:55
I'm closing it for now :)

**Closed as completed by voronianski** 2016-04-08 08:55 UTC
